CREATE TABLE D_ACTIVITE(
    ID_ACT          SERIAL  PRIMARY KEY,
    URL             TEXT    NOT NULL,
    TITRE           TEXT    NOT NULL,
    CHAPEAU         TEXT,
    DESCRIPTION     TEXT,
    DATE_DEBUT      TEXT,
    DATE_FIN        TEXT,
    OCCURENCE       TEXT,
    IMAGE           TEXT,
    MOTS_CLES       TEXT,
    NOM_LIEU        TEXT,
    ADRESSE         TEXT,
    CODE_POSTAL     TEXT,
    VILLE           TEXT,
    COORDONNEES     TEXT,
    WEBSITE         TEXT,
    PHONE           TEXT,
    EMAIL           TEXT,
    FACEBOOK        TEXT,
    TWITTER         TEXT,
    TYPE_PRIX       TEXT,
    DETAIL_PRIX     TEXT,
    URL_RESERVATION TEXT,
    AUDIENCE        TEXT,
    FILENAME        TEXT,
    DATE_INSERT     TIMESTAMP   WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DATE_UPDATE     TIMESTAMP   WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DELETE_LINE     INTEGER DEFAULT 0
);

CREATE TABLE D_COMMERCE(
    ID_COM          SERIAL  PRIMARY KEY,
    TITRE           TEXT    NOT NULL,
    ADRESSE         TEXT,
    CODE_POSTAL     TEXT,
    TYPE_COMMERCE   TEXT,
    FABRIQUER_PARIS TEXT,
    SERVICE         TEXT,
    DESCRIPTION     TEXT,
    PRECISION       TEXT,
    WEBSITE         TEXT,
    PHONE           TEXT,
    EMAIL           TEXT,
    COORDONNEES     TEXT,
    FILENAME        TEXT,
    DATE_INSERT     TIMESTAMP   WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DATE_UPDATE     TIMESTAMP   WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DELETE_LINE     INTEGER DEFAULT 0
);

CREATE VIEW V_D_COMMERCE AS
SELECT
ID_COM,TITRE,ADRESSE,CODE_POSTAL,TYPE_COMMERCE,
FABRIQUER_PARIS,SERVICE,DESCRIPTION,PRECISION,
WEBSITE,PHONE,EMAIL,COORDONNEES
FROM D_COMMERCE
WHERE DELETE_LINE = 0 AND
coordonnees IS NOT NULL
AND coordonnees <> '';

CREATE VIEW V_D_SIMPLE_COMMERCE AS
SELECT
ID_COM,TITRE,COORDONNEES
FROM D_COMMERCE
WHERE DELETE_LINE = 0 
AND coordonnees IS NOT NULL
AND coordonnees <> '';

CREATE VIEW V_D_ACTIVITE AS
SELECT
ID_ACT,URL,TITRE,CHAPEAU,DESCRIPTION,DATE_DEBUT,
DATE_FIN,OCCURENCE,IMAGE,MOTS_CLES,NOM_LIEU,
ADRESSE,CODE_POSTAL,VILLE,COORDONNEES,WEBSITE,
PHONE,EMAIL,FACEBOOK,TWITTER,TYPE_PRIX,DETAIL_PRIX,
URL_RESERVATION,AUDIENCE
FROM D_ACTIVITE
WHERE DELETE_LINE = 0
AND coordonnees IS NOT NULL
AND coordonnees <> '';

CREATE VIEW V_D_SIMPLE_ACTIVITE AS
SELECT
ID_ACT,TITRE,COORDONNEES
FROM D_ACTIVITE
WHERE DELETE_LINE = 0
AND coordonnees IS NOT NULL
AND coordonnees <> '';
